user_role_message.settings:
  type: mapping
  label: 'User Role Message settings'
  mapping:
    message:
      type: string
      label: 'Message'
    user_roles:
      type: condition.plugin.user_role
      label: 'User Role Condition'
